---
title: "The Politics and Income Inequality: The United States Example"
author: 
  - Atay, Fatih[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 19080380, [Github Repo](https://github.com/atayfatih/midterm)


# Introduction
The Income inequality is on the agenda as a problem that still maintains its importance all over the world. The United States is one of the countries that suffer from this issue.Although the country is located at an important point in the world in economic terms, income inequality has become one of the main sources of problems at significant points in the country's agenda. Income inequality should be addressed not only as a financial issue, but also as a social justice issue. The politics of income inequality in the United States will be examined and discussed more closely in this study. In this context, the available data will be shed light on and it will be examined whether there is a correlation between different variables.

## Literature Review

While there are many articles discussing this issue in general, some of the articles focus on the relationship between politics and income inequality in the USA. For example, one of the article explores power resources, and politics in an income inequality context [@jacobs2016politics]. The authors contend that the influence of political institutions on economic outcomes is the prominent factor, and the gap between different income groups might be caused by these institutions and decision-makers. The results show that the most important drivers are growth in the political power of neoliberal national governments. In another article, “Political Polarization and Income Inequality”, the relationship between voting and income is trying to be explained and examined with statistical information [@mccarty2003political]. The essay by Pikkety examines long-term patterns in income inequality throughout the course of the 20th century in the United States. Along with examining the overall trend from various perspectives, the author also offers solutions to this problem [@piketty2003income]. 

The Gini coefficient, the top 1% of earners, and intergenerational mobility are just a few of the tools the writers use to analyze income and wealth inequality. Additionally, some of them cover the social and political ramifications of economic inequality and propose legislative remedies including progressive taxation and financial expenditures in social and educational initiatives [@strickland1999examination].





\newpage
# References {#references}
<div id="refs"></div>

